services:
  #########################################################
  init-rsync:
    image: secoresearch/rsync:ubuntu
    user: root:root
    command:
      - bash
      - -c
      - |
        set -ue
        rsync --delete -av /src/src /app/
        rsync --delete -av /src/public /app/
        rsync --delete -av /src/.env /app/
        rsync --delete -av /src/next.config.js /app/
        rsync --delete -av /src/next-env.d.ts /app/
        rsync --delete -av /src/package.json /app/
        rsync --delete -av /src/package-lock.json /app/
        rsync --delete -av /src/postcss.config.mjs /app/
        rsync --delete -av /src/tailwind.config.ts /app/
        rsync --delete -av /src/tsconfig.json /app/
    working_dir: /src
    volumes:
      - type: bind
        source: .
        target: /src
      - type: volume
        source: app-data
        target: /app
  #########################################################
  front-init:
    image: node
    command:
      - npm
      - ci
    depends_on:
      init-rsync:
        condition: service_completed_successfully
    working_dir: /app
    volumes:
      - type: volume
        source: app-data
        target: /app
      - type: volume
        source: root
        target: /root
  #########################################################
  front-test:
    image: node
    command:
      - npm
      - run
      - build
    depends_on:
      init-rsync:
        condition: service_completed_successfully
      front-init:
        condition: service_completed_successfully
    working_dir: /app
    volumes:
      - type: volume
        source: app-data
        target: /app
      - type: volume
        source: root
        target: /root
  #########################################################
volumes:
  app-data:
  root:
