version: "3.7"
services:
  #########################################################
  openapi-generator:
    image: node:22-bookworm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src/app:/app
    command:
      - bash
      - -c
      - |
        mkdir -p /app/_api/
        npx openapi-zod-client https://hew-dev-api.kigawa.net/openapi.json -o /app/_api/client.ts
        npx openapi-zod-client https://hew-dev-image.kigawa.net/openapi.json -o /app/_api/imgClient.ts
        # npx openapi-zod-client http://host.docker.internal:8000/openapi.json -o /app/_api/client.ts
        chmod 777 -R /app/_api/
volumes:
  app-data-openapi:
  db-data-openapi: