import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


// 共通のmetaタグ
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// 共通の見た目
export default function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <html>
        <head />
        <body>{children}</body>
        </html>
    )
}