on:
  push:
jobs:
  test:
    if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/test.yml
  cd:
    strategy:
      matrix:
        branch:
          - ref: "refs/heads/develop"
            manifestFile: ./hew-dev/front/front.yml
            name: hew-front
            keycloakBaseUrl: "https://user.kigawa.net"
            keycloakRealms: "develop"
            siteUrl: "https://hew-dev.kigawa.net"
            baseUrl: "https://hew-dev-api.kigawa.net/"
            imgBaseUrl: "https://hew-dev-image.kigawa.net/"
          - ref: "refs/heads/main"
            manifestFile: ./diver/front/front.yml
            name: diver
            keycloakBaseUrl: "https://user.kigawa.net"
            keycloakRealms: "diver"
            siteUrl: "https://diver.kigawa.net"
            baseUrl: "https://diver-api.kigawa.net/"
            imgBaseUrl: "https://diver-image.kigawa.net/"

    runs-on: ubuntu-latest
#    needs: [test]
    env:
      preDockerBuildCmd: ""
      repository: HAL-IAIH-team-F/k8s-hew
      manifestFile: ${{ matrix.branch.manifestFile }}
      dockerFile: Dockerfile
      harborUser: robot$hew
      name: ${{ matrix.branch.name }}
      dockerArg: |
        keycloakId=${{ secrets.KEYCLOAK_ID }}
        keycloakSecret=${{ secrets.KEYCLOAK_SECRET }}
        keycloakBaseUrl=${{ matrix.branch.keycloakBaseUrl }}
        authSecret=${{ secrets.AUTH_SECRET }}
        keycloakRealms=${{ matrix.branch.keycloakRealms }}
        siteUrl=${{ matrix.branch.siteUrl }}
        baseUrl=${{ matrix.branch.baseUrl }}
        imgBaseUrl=${{ matrix.branch.imgBaseUrl }}
      dir: ./

    steps:
      # checkout
      - run: echo ${{ github.ref }} ${{ github.ref == matrix.branch.ref }}
      - uses: actions/checkout@v4
        if: github.ref == matrix.branch.ref
      - run: exit 1
      - name: preBuild
        if: github.ref == matrix.branch.ref && env.preDockerBuildCmd
        run: ${{ env.preDockerBuildCmd }}

      # docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: github.ref == 'refs/heads/${{ matrix.branch.ref }}'
      - uses: docker/login-action@v3
        if: github.ref == 'refs/heads/${{ matrix.branch.ref }}'
        with:
          registry: harbor.kigawa.net
          username: ${{ env.harborUser }}
          password: ${{ secrets.HARBOR_PASS }}

#      - name: BuildAndPushImageOnHarbor
#        run: |
#          docker build -t harbor.kigawa.net/private/${{ env.name }}:${{ github.ref_name }}-${{ github.sha }} \
#           -f ${{ env.dockerFile }} \
#          ${{ env.dockerArg }} \
#          ./
#          docker push harbor.kigawa.net/private/${{ env.name }}:${{ github.ref_name }}-${{ github.sha }}

      - uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/${{ matrix.branch.ref }}'
        with:
          context: ${{ env.dir }}
          file: ${{ env.dir }}/${{ env.dockerFile }}
          push: true
          tags: harbor.kigawa.net/private/${{ env.name }}:${{ github.ref_name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ env.dockerArg }}


      # argo
      - name: checkout manifest repository
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/${{ matrix.branch.ref }}'
        with:
          repository: ${{ env.repository }}
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update YAML File
        if: github.ref == 'refs/heads/${{ matrix.branch.ref }}'
        run: |
          yq -i '.spec.template.spec.containers[0].image = "harbor.kigawa.net/private/${{ env.name }}:${{ github.ref_name }}-${{ github.sha }}"' \
          ${{ env.manifestFile }}

      - name: push
        if: github.ref == 'refs/heads/${{ matrix.branch.ref }}'
        run: |
          git config user.name githubActions
          git config user.email bot@kigawa.net
          git add .
          git commit --author=. -m "update rev"
          git push
