on:
  push:
jobs:
  test:
    uses: ./.github/workflows/test.yml
  cd:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
#    needs: [test]
    env:
      preDockerBuildCmd: ""
      repository: HAL-IAIH-team-F/k8s-hew
      manifestFile: ./hew-dev/front/front.yml
      dockerFile: Dockerfile
      harborUser: robot$hew
      name: hew-front
      dockerArg: |
        keycloakId=${{ secrets.KEYCLOAK_ID }}
        keycloakSecret=${{ secrets.KEYCLOAK_SECRET }}
        keycloakBaseUrl="https://user.kigawa.net"
        authSecret=${{ secrets.AUTH_SECRET }}
        keycloakRealms="develop"
        siteUrl="https://hew-dev.kigawa.net"
        baseUrl="https://hew-dev-api.kigawa.net/"
        imgBaseUrl="https://hew-dev-image.kigawa.net/"
      dir: ./
    steps:
      # checkout
      - uses: actions/checkout@v4

      - name: preBuild
        if: ${{ env.preDockerBuildCmd }}
        run: ${{ env.preDockerBuildCmd }}

      # docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: harbor.kigawa.net
          username: ${{ env.harborUser }}
          password: ${{ secrets.HARBOR_PASS }}

#      - name: BuildAndPushImageOnHarbor
#        run: |
#          docker build -t harbor.kigawa.net/private/${{ env.name }}:${{ github.ref_name }}-${{ github.sha }} \
#           -f ${{ env.dockerFile }} \
#          ${{ env.dockerArg }} \
#          ./
#          docker push harbor.kigawa.net/private/${{ env.name }}:${{ github.ref_name }}-${{ github.sha }}

      - uses: docker/build-push-action@v5
        with:
          context: ${{ env.dir }}
          file: ${{ env.dir }}/${{ env.dockerFile }}
          push: true
          tags: harbor.kigawa.net/private/${{ env.name }}:${{ github.ref_name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ env.dockerArg }}


      # argo
      - name: checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.repository }}
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update YAML File
        run: |
          yq -i '.spec.template.spec.containers[0].image = "harbor.kigawa.net/private/${{ env.name }}:${{ github.ref_name }}-${{ github.sha }}"' \
          ${{ env.manifestFile }}

      - name: push
        run: |
          git config user.name githubActions
          git config user.email bot@kigawa.net
          git add .
          git commit --author=. -m "update rev"
          git push
