name: test

on: [push]

jobs:
  back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.test.yml up front-test --exit-code-from front-test