name: test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.test.yml up front-test --exit-code-from front-test
      - run: docker compose -f docker-compose.test.yml logs
        if: always()
        